<?php


/**
 * Skeleton subclass for performing query and update operations on the 'jobeet_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Feb 21 10:15:45 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetCategoryPeer extends BaseJobeetCategoryPeer {

	static public function doSelectActive(Criteria $criteria)
	{
		//TODO
		return self::doSelectOne($criteria);
	}
	
  static public function getWithJobs($category)
	{
		$criteria = new Criteria();
		$criteria->addJoin(self::ID, JobeetJobPeer::CATEGORY_ID);
		$criteria->add(JobeetJobPeer::EXPIRES_AT, time(), Criteria::GREATER_THAN);

		if (!is_null($category))
		{
			$criteria->add(JobeetCategoryPeer::ID, $category->getId());
		}

		$criteria->setDistinct();

		return self::doSelect($criteria);
	}

	static public function getJobsByCategory()
	{
		return $this->getWithJobs($criteria);
	}

} // JobeetCategoryPeer
